# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'Viaje Com Darcy' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Viaje Com Darcy
  
  # Infrastructure
  pod 'Swinject', '1.1.2'
  
  pod 'Fabric', '1.6.7'
  pod 'Crashlytics', '3.7.2'
    
  # Parse
  pod 'Parse', '1.13.0'

  target 'Viaje Com DarcyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Viaje Com DarcyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
