# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Viaje Com Darcy' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Viaje Com Darcy
    
  # Parse
  pod 'Parse', '1.13.0'

  target 'Viaje Com DarcyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Viaje Com DarcyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
